version: '3'

services:

  # server:
  #   image: e-commerce-server
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db  
    
  db:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    volumes:
    - mongodb:/my/own/datadir

volumes:
  mongodb:
    